@extends('layouts.app')
@section('content')
<section class="relative overflow-hidden"><div class="absolute -left-24 top-10 h-72 w-72 rounded-full bg-[#e5eee8] blur-3xl"></div><div class="absolute -right-20 top-0 h-80 w-80 rounded-full bg-[#f0e5d2] blur-3xl"></div><div class="relative mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-24">
 <div><span class="badge">Hair appointments, simplified</span><h1 class="mt-5 max-w-3xl font-display text-5xl leading-[.98] tracking-[-.04em] text-deep sm:text-6xl">Your hair deserves a booking experience this beautiful.</h1><p class="mt-6 max-w-xl text-lg leading-8 text-gray-600">Find your service, choose your professional, pick a time, and leave the rest to us.</p><div class="mt-8 flex flex-wrap gap-3"><a class="btn-primary" href="{{ route('booking.create') }}">Book an appointment</a><a class="btn-soft" href="{{ route('services') }}">Explore services</a></div><div class="mt-8 flex gap-8 text-sm text-gray-500"><div><strong class="block text-xl text-deep">Easy</strong>online booking</div><div><strong class="block text-xl text-deep">Personal</strong>professional matching</div><div><strong class="block text-xl text-deep">Modern</strong>salon care</div></div></div>
 <div class="card relative min-h-[440px] overflow-hidden bg-[#ebe4d9] p-6"><div class="absolute inset-0 bg-[radial-gradient(circle_at_30%_30%,rgba(255,255,255,.75),transparent_32%),linear-gradient(145deg,#e9e2d5,#cfdace)]"></div><div class="relative flex h-full flex-col justify-between"><span class="self-end rounded-full bg-white/75 px-4 py-2 text-xs font-semibold tracking-wide text-deep backdrop-blur">Easyhairsolutions STUDIO</span><div><p class="font-display text-4xl leading-tight text-deep">Good hair days<br>start here.</p><p class="mt-3 max-w-xs text-sm leading-6 text-deep/70">A calm, clear way to book the care you actually want.</p></div></div></div>
</div></section>
<section class="bg-deep py-16 text-white"><div class="mx-auto max-w-7xl px-5 lg:px-8"><div class="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><span class="text-xs font-semibold uppercase tracking-[.18em] text-[#c9d8d0]">Signature services</span><h2 class="mt-3 font-display text-4xl">Book what fits your hair.</h2></div><a href="{{ route('services') }}" class="btn-soft w-fit">View all services</a></div><div class="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">@foreach($services as $service)<a href="{{ route('booking.create',['service'=>$service->id]) }}" class="rounded-3xl border border-white/10 bg-white/5 p-6 transition hover:bg-white/10"><div class="flex items-start justify-between gap-5"><div><span class="text-xs uppercase tracking-[.14em] text-[#c9d8d0]">{{ $service->category }}</span><h3 class="mt-2 text-xl font-semibold">{{ $service->name }}</h3><p class="mt-2 text-sm leading-6 text-white/60">{{ $service->description }}</p></div><span class="text-sm text-white/70">${{ number_format($service->price,0) }}</span></div><div class="mt-6 text-sm text-[#dfe9e4]">{{ $service->duration_minutes }} min <span class="mx-2 text-white/30">•</span> Book →</div></a>@endforeach</div></div></section>
<section class="py-20"><div class="mx-auto max-w-7xl px-5 lg:px-8"><div class="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><span class="badge">Meet the professionals</span><h2 class="mt-4 font-display text-4xl tracking-[-.03em]">People first.<br>Hair second. Results always.</h2><p class="mt-4 max-w-md leading-7 text-gray-600">Easyhairsolutions puts the professional relationship at the center of booking, from your first appointment to your next.</p></div><div class="grid gap-4 sm:grid-cols-3">@foreach($professionals as $professional)<div class="card p-5"><div class="flex h-20 w-20 items-center justify-center rounded-2xl bg-cream font-display text-2xl text-sage">{{ collect(explode(' ',$professional->user->name))->map(fn($x)=>substr($x,0,1))->join('') }}</div><h3 class="mt-4 font-semibold">{{ $professional->user->name }}</h3><p class="mt-1 text-sm text-gray-500">{{ implode(' · ', $professional->specialties ?? []) }}</p></div>@endforeach</div></div></div></section>
<section class="border-y border-line bg-cream py-16"><div class="mx-auto max-w-7xl px-5 lg:px-8"><div class="flex items-end justify-between"><div><span class="badge bg-white">Studio shop</span><h2 class="mt-3 font-display text-4xl">Care between appointments.</h2></div><a href="{{ route('shop') }}" class="btn-soft">Shop all</a></div><div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach($products as $product)<div class="rounded-3xl border border-line bg-white p-5"><div class="flex aspect-[4/3] items-end rounded-2xl bg-[#efe9df] p-4"><span class="rounded-full bg-white/80 px-3 py-1 text-xs">Easyhairsolutions essential</span></div><h3 class="mt-4 font-semibold">{{ $product->name }}</h3><div class="mt-2 flex items-center justify-between"><span class="text-gray-500">${{ number_format($product->price,2) }}</span><form method="POST" action="{{ route('cart.add',$product) }}">@csrf<button class="text-sm font-semibold text-sage">Add +</button></form></div></div>@endforeach</div></div></section>
@endsection
